spring.application.name=dio-spring-security-jwt
N2Y2YzM2ODI3Nzk3YTkxZTczNmNmMmM3Yzc4ZTZmYzdhZDEzNzFkZmYzOTM2NTc3N2Q=
security.config.prefix=Bearer
security.config.expiration=3600000
server.port=8081
##H2 Database Connection Properties
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql: true
spring.h2.console.enabled=true
logging.level.org.springframework.boot=DEBUG
logging.level.org.springframework.web=DEBUG
