spring.application.name=aula-spring-data-jpa
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossTransactionManagerLookup
spring.jpa.hibernate.ddl-auto=update



