spring.application.name=api-spring-boot
# Habilitar o Swagger UI
springdoc.swagger-ui.enabled=true

# Definir o caminho para o Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Habilitar a documentação OpenAPI
springdoc.api-docs.enabled=true